---
title: Introduction to Raspberry Pi Pico with breadboard projects
hero_image: images/banner.png
description: Recipes and diagrams for building simple projects with the Raspberry Pi Pico using a breadboard and components.
version: 4
listed: false
copyedit: false
last_tested: '2024-01-31'
steps:
- title: Introduction
- title: Meet Raspberry Pi Pico
- title: Install Thonny
- title: Add the MicroPython firmware
- title: Use the picozero library
- title: Use the shell
- title: Resistors
- title: LEDs
- title: RGB LEDs
- title: Passive Buzzers
- title: Buttons and switches
- title: Potentiometers
- title: Powering your Pico
- title: Our Raspberry Pi Pico projects
